### ISSUE TITLE
3d_sense_multiview.npy data

### ISSUE THREAD

**Issue by sxhzju** [xing-shuai/PaperDemoAndExampleTest#1]
Excellent work of visualizing human3.6m! But could you please provide me with the `3d_sense_multiview.npy`?
I also send an Email to your gmail.

**Comment by xing-shuai** [comment]
https://mega.nz/file/rm4yzSIB#IDPBPzO3sck2zBPitcAuo3aS213d4E81fxUbvkzmNhk

**Comment by xing-shuai** [comment]
The link to 3d_sense_multiview.npy
